# Generated by Django 3.2.2 on 2021-05-18 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrental', '0008_payment2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardholdername', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('cvv', models.IntegerField()),
                ('cardnumber', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Payment2',
        ),
    ]
